#!/bin/bash

mongodump --uri "mongodb://${DB_AUTH}@${DB_ADDRESS}/e-flex" --excludeCollection auth_states --excludeCollection errors --excludeCollection users

# remove expiration from users, which contains sensible login info
mongoexport --uri "mongodb://${DB_AUTH}@${DB_ADDRESS}/e-flex" -c users | sed s/,\"expiration\":{[^}]*}//g > dump/e-flex/users.json

DEST=dump/`date +%Y-%m-%d`
if [ -e $DEST ]; then
    rm -fr $DEST
fi
mv dump/e-flex $DEST